### ISSUE TITLE
点击存在延迟问题

### ISSUE THREAD

**Issue by gongfuture** [BlueYeeeee/Rizline-AutoDot#1]
如题，歌曲开始后识别第一个点击存在问题
该脚本是否不再维护？

**Comment by BlueYeeeee** [comment]
新版本疑似把延迟这些都改了，我今天看看能不能改一下

**Comment by gongfuture** [comment]
> 新版本疑似把延迟这些都改了，我今天看看能不能改一下

好嘞谢谢您嘞，顺便问下源代码是如何构建apk的？我原本想自己改的，但是不知道怎么构建

**Comment by BlueYeeeee** [comment]
目前排查到问题了，是因为Rizline屏蔽了过短时间点击的问题，我把每次点击的延迟加上去
我是怕构建方法发出来他们就可以针对了，所以我只是公开了源码，没有公开构建教程，你可以网上自己找找~

**Comment by BlueYeeeee** [comment]
已经改成新版本了，看看你那边能不能稳定运行

**Comment by gongfuture** [comment]
> 已经改成新版本了，看看你那边能不能稳定运行

好的，现在在外面，晚上回去试一下

**Comment by gongfuture** [comment]
> 已经改成新版本了，看看你那边能不能稳定运行

新版本通不过开屏等待
模拟器版本9.0.71.2
![image](https://github.com/user-attachments/assets/c35f50d2-fd80-4a37-ae6a-e5f64865025a)

**Comment by BlueYeeeee** [comment]
是不是没有Root还是什么，应该不会这样的

**Comment by gongfuture** [comment]
> 是不是没有Root还是什么，应该不会这样的

root开了也给了，上个版本还能打开运行，这版本就不行了（）
系统: Microsoft Windows 10 64位 22H2
CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
主板: 雷神 NLZA
内存: 可用内存(3.9GB) 内存(15.7GB)
屏幕: 2560x1440【当前使用】
屏幕: 1050x1680
显卡: NVIDIA GeForce RTX 3060 Laptop GPU(20240625)【当前使用】
显卡: USB Mobile Monitor Virtual Display(20210831)
OpenGL: 4.6.0 NVIDIA 556.12
VT:已开启
HyperV:已关闭
Root:开启
以管理员身份运行: 否
安装磁盘: E盘(SSD-NTFS) 可用空间(148GB) 总空间(931GB)
模拟器版本: 9.0.71.2(64)
运行参数: CPU(4核) 内存(4096M) 分辨率(1280x720 DPI 240) FPS(60)
多开参数: 当前序号(0) 正在运行(1) 高速模式(1) FPS限制(60)
可用空间: 类型(自动扩充) 可用空间(22GB) 总空间(24GB)
机型: 品牌(HUAWEI) 型号(OXF-AN00)
ASTC: 开启
ROOT 权限: 开启
模拟器路径: E:\leidian\LDPlayer9\
日志路径: C:\Users\gongf\AppData\Roaming\leidian9\log

**Comment by BlueYeeeee** [comment]
我知道了，我调用了OCR但是没有把本地OCR打包进去（

**Comment by BlueYeeeee** [comment]
我再看看吧，因为我之前是直接在编译器里面运行的，没有打包过

**Comment by BlueYeeeee** [comment]
打包好了，我试过可以打开了，是封装的时候没有把arm和x86都封装的原因

**Comment by BlueYeeeee** [comment]
如果没问题的话我就关闭issue了
