### ISSUE TITLE
回血段长条出现漏击问题

### ISSUE THREAD

**Issue by gongfuture** [BlueYeeeee/Rizline-AutoDot#2]
回血段长条点击似乎过迟导致有时点击不上，似乎是更改的点击逻辑导致的延迟？
其次这一段的代码似乎没有正确执行，导致每次打时到达`phase 2`前会失败，然后`phase 2`开始下一把
https://github.com/BlueYeeeee/Rizline-AutoDot/blob/e2c2569104a7eaac65af79c21815c8a5a5ce8bb7/Rizline/%E8%84%9A%E6%9C%AC/Rizline.lua#L111-L119

然后在代码里发现长条段
https://github.com/BlueYeeeee/Rizline-AutoDot/blob/e2c2569104a7eaac65af79c21815c8a5a5ce8bb7/Rizline/%E8%84%9A%E6%9C%AC/Rizline.lua#L125-L130
其中
``` lua
	touchUp(1)
	touchDown(1,638,364)
```
这样的写法是否会导致此类问题？

**Comment by gongfuture** [comment]
另，搜了好久还是没找到这是用什么方法构建apk的（）

**Comment by BlueYeeeee** [comment]
不是，这个应该就是点太晚导致的，我改一下延迟

**Comment by BlueYeeeee** [comment]
if cmpColorEx(血条,0.9)==0 then 
 	touchUp(1) 
     swipe(260,379,520,362,100) 
     sleep(200) 
     swipe(520,362,1020,362,100) 
     restime=restime+1 
     toast("血不够打完，直接重开",0,0,12) 
     breakflag=true 
     sleep(2000) 

这一段仅是做了开头的检测。
我本来是单开了一个线程来判断整局游戏是否Failed的，但是那段代码反而影响到了整体的稳定性，所以后来我删掉了

**Comment by BlueYeeeee** [comment]
看看现在的版本

**Comment by gongfuture** [comment]
> 看看现在的版本

非常诡异，我是双屏电脑，一屏幕180hz一屏幕60hz，模拟器放在俩屏幕上打出来延迟不一样（）
我再多测几次

**Comment by gongfuture** [comment]
> > 看看现在的版本
> 
> 非常诡异，我是双屏电脑，一屏幕180hz一屏幕60hz，模拟器放在俩屏幕上打出来延迟不一样（） 我再多测几次

https://github.com/user-attachments/assets/94f4cf21-0518-4dc9-b480-1b29b0f33328

刚装上的时候有过两三次满分，不过长条冒late，然后就开始存在漏击，整体稳定下来大概是这个样子。
大体是越往后越容易出现late，不过不会像之前直接断一堆导致失败，跑倒是能跑了
然后不知道是不是这个版本用来测试的原因，打完一遍就会自动结束

总之就是适配地狱（

**Comment by BlueYeeeee** [comment]
> > > 看看现在的版本
> > 
> > 
> > 非常诡异，我是双屏电脑，一屏幕180hz一屏幕60hz，模拟器放在俩屏幕上打出来延迟不一样（） 我再多测几次
> 
>  bandicam.2024-08-07.18-07-29-549.mp4 
> 刚装上的时候有过两三次满分，不过长条冒late，然后就开始存在漏击，整体稳定下来大概是这个样子。 大体是越往后越容易出现late，不过不会像之前直接断一堆导致失败，跑倒是能跑了 然后不知道是不是这个版本用来测试的原因，打完一遍就会自动结束
> 
> 总之就是适配地狱（

我是180hz和144hz屏测的，所以不知道60hz屏是什么情况（）

**Comment by BlueYeeeee** [comment]
你要把运行前的各种Dot判断都关了？因为另外一个手动Dot目标设置的我把代码删了，Dot溢出判断的没删

**Comment by gongfuture** [comment]
> > > > 看看现在的版本
> > > 
> > > 
> > > 非常诡异，我是双屏电脑，一屏幕180hz一屏幕60hz，模拟器放在俩屏幕上打出来延迟不一样（） 我再多测几次
> > 
> > 
> > bandicam.2024-08-07.18-07-29-549.mp4
> > 刚装上的时候有过两三次满分，不过长条冒late，然后就开始存在漏击，整体稳定下来大概是这个样子。 大体是越往后越容易出现late，不过不会像之前直接断一堆导致失败，跑倒是能跑了 然后不知道是不是这个版本用来测试的原因，打完一遍就会自动结束
> > 总之就是适配地狱（
> 
> 我是180hz和144hz屏测的，所以不知道60hz屏是什么情况（）

原来是这样，我说我怎么180还可以60不行（）

**Comment by BlueYeeeee** [comment]
但是奇怪的是，模拟器只有60Hz。为什么主屏幕刷新率会影响模拟器脚本运行情况啊草（

**Comment by gongfuture** [comment]
> 但是奇怪的是，模拟器只有60Hz。为什么主屏幕刷新率会影响模拟器脚本运行情况啊草（

所以我才说是诡异的适配地狱啊（
