### ISSUE TITLE
无法自动开始下一次打歌

### ISSUE THREAD

**Issue by gongfuture** [BlueYeeeee/Rizline-AutoDot#3]
我又来提issue了(
目前是dot溢出停止和目标dot无论怎么开关都不会进行下一次打歌
目标dot设置的2000，已获得为0

**Comment by gongfuture** [comment]
要不直接改无限循环吧，过一阵子过去买点东西（）

upd：这样子甚至都不用写dot相关判定了

**Comment by BlueYeeeee** [comment]
> 要不直接改无限循环吧，过一阵子过去买点东西（）
> 
> upd：这样子甚至都不用写dot相关判定了

我草，你不知道我为了识别Dot花了多少精力啊（）
算了，那这样我就删了就留一个溢出判定吧
